In [1]:
import torch
from torch.autograd import Variable

In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [3]:
x_data = Variable(torch.Tensor([[1.0], [2.0], [3.0]])).to(device)
y_data = Variable(torch.Tensor([[2.0], [4.0], [6.0]])).to(device)

In [4]:
x_data,y_data

(tensor([[1.],
         [2.],
         [3.]], device='cuda:0'),
 tensor([[2.],
         [4.],
         [6.]], device='cuda:0'))

In [5]:
class LinearRegressionModel(torch.nn.Module): 
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.linear = torch.nn.Linear(1, 1)  # One in and one out 
    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

In [6]:
our_model = LinearRegressionModel()
our_model.to(device)
print(our_model)

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


In [7]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(our_model.parameters(),  lr = 0.01)

In [8]:
for epoch in range(1000):
 
    # Forward pass: Compute predicted y by passing 
    # x to the model
    pred_y = our_model(x_data)
 
    # Compute and print loss
    loss = criterion(pred_y, y_data)
 
    # Zero gradients, perform a backward pass, 
    # and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch%100) ==0:
        print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 0, loss 10.381362915039062
epoch 100, loss 0.014120868407189846
epoch 200, loss 0.008725810796022415
epoch 300, loss 0.005392034538090229
epoch 400, loss 0.003331931075081229
epoch 500, loss 0.0020589332561939955
epoch 600, loss 0.0012723091058433056
epoch 700, loss 0.0007861863123252988
epoch 800, loss 0.00048581507871858776
epoch 900, loss 0.0003002097364515066


In [9]:
new_var = Variable(torch.Tensor([[4.0]])).to(device)
pred_y = our_model(new_var)
print("predict (after training)", 4, our_model(new_var).item())

predict (after training) 4 8.027315139770508


In [10]:
new_var

tensor([[4.]], device='cuda:0')

In [11]:
pred_y 

tensor([[8.0273]], device='cuda:0', grad_fn=<AddmmBackward0>)